# Github workflow to compile latex and deploy the pdf to an orphan branch.
# adapted from the original code made by: 
# Davide Gerosa (2021) https://github.com/dgerosa

name: writeapaper
on: [push]
jobs:
  paper:
    runs-on: ubuntu-latest
    env:
      # Edit here with the names of your latex file and directory (can use ".")
      DIR: ./
      FILE: blank
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Install TeXlive
      #   run: sudo apt-get update && sudo apt-get install texlive texlive-publishers texlive-science latexmk cm-super
      # - name: LaTeX compile 1
      #   working-directory: ${{ env.DIR }}
      #   #run: latexmk -pdf -bibtex ${{ env.FILE }}
      #   run: pdflatex ${{ env.FILE }};
      # - name: Bibtex compile
      #   continue-on-error: true
      #   working-directory: ${{ env.DIR }}
      #   run: bibtex ${{ env.FILE }};
      # - name: LaTeX compile 2
      #   working-directory: ${{ env.DIR }}
      #   run: pdflatex ${{ env.FILE }}; pdflatex ${{ env.FILE }};
      - name: LaTex
        uses: xu-cheng/texlive-action@v2
        with:
          run: |
            cd ${{ env.DIR }}
            pdflatex ${{ env.FILE }}
            biber ${{ env.FILE }}
            pdflatex ${{ env.FILE }}
            pdflatex ${{ env.FILE }}
      - name: move
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/${{ env.FILE }}.pdf ./github_artifacts/
      - name: create readme file
        run: |
            touch ./github_artifacts/readme.md
            printf "Brouillon de manuscrit de thèse\n- [blank](https://github.com/vbkantoine/thesis/blob/build/blank.pdf)\n" > ./github_artifacts/readme.md
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE }}.pdf
          path: ./github_artifacts
  deploy:
    # Edit here if compiling multiple papers
    needs: [paper]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: github_artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy
      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
